In [72]:
import numpy as np

In [73]:
p=input("enter your 2 letters to be encrypted using hill cipher ")

enter your 2 letters to be encrypted using hill cipher mi


In [74]:
p=p.upper()

In [75]:
p

'MI'

In [76]:
letter_index={}

In [77]:
for i in range(65,91):
  letter_index.update({chr(i):i-65})

In [78]:
letter_index

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

In [79]:
mat_p=np.array([letter_index[p[0]],letter_index[p[1]]])

In [80]:
mat_p

array([12,  8])

In [81]:
mat_p=mat_p.reshape(2,1)

In [90]:
k=np.array([[3,25],[24,17]])

In [91]:
k.shape

(2, 2)

#Encryption:
we use formula as

    C=KP mod 26

In [92]:
c=np.matmul(k,mat_p)

In [93]:
c=c%26

In [94]:
c

array([[2],
       [8]])

In [95]:
outpt=np.array([])

In [96]:
for key in letter_index:
  for i in range(len(c)):
    if(letter_index[key]==c[i,0]):
      outpt=np.append(outpt,key)

In [97]:
outpt

array(['C', 'I'], dtype='<U32')

In [98]:
outpt_str="your encrepted text is:"

In [99]:
for values in outpt:
  outpt_str=outpt_str+values

In [100]:
outpt_str

'your encrepted text is:CI'

#Decryption:
we use

    P=k(-1)C mod 26

In [114]:
determinant=np.linalg.det(k)

In [115]:
determinant

-548.9999999999999

In [116]:
if(abs(determinant)>25):
  if determinant>0:
    determinant=determinant%26
  else:
    determinant=-1*(abs(determinant)%26)+26

In [117]:
determinant

23.000000000000114

#Adjust adjoint manually

In [151]:
adjoint=np.array([[17,-25],[-24,3]])

In [152]:
adjoint

array([[ 17, -25],
       [-24,   3]])

In [153]:
adjoint=adjoint.astype(int)

In [154]:
adjoint

array([[ 17, -25],
       [-24,   3]])

In [155]:
determinant=int(determinant)

In [156]:
inverse=adjoint/determinant

In [157]:
inverse

array([[ 0.73913043, -1.08695652],
       [-1.04347826,  0.13043478]])

#here if floatig point value is obtained we need to do using another method

In [193]:
for i in range(100):
  value=(1+26*i)/determinant
  if(value-int(value)<0.001):
    break

In [194]:
value

17.0

In [195]:
value=int(value)

In [196]:
inverse=value*adjoint

In [197]:
inverse

array([[ 289, -425],
       [-408,   51]])

In [201]:
for i in range(2):
  for j in range(2):
    print(inverse[i,j])
    if(inverse[i,j]<0):
      k=1*(inverse[i,j]%26)
      #print(k)
      inverse[i,j]=k
      #print(inverse[i,j])
    else:

      inverse[i,j]=inverse[i,j]%26


289
-425
-408
51


In [202]:
inverse

array([[ 3, 17],
       [ 8, 25]])

#Now decryption
using:

    k-1c mod 26

In [203]:
decrypted=np.matmul(inverse,c)

In [205]:
c

array([[2],
       [8]])

In [206]:
inverse

array([[ 3, 17],
       [ 8, 25]])

In [207]:
decryp=np.matmul(inverse,c)

In [208]:
decryp=decryp%26

In [210]:
decryp

array([[12],
       [ 8]])

In [231]:
output_str="your decryped value is :"

In [232]:
outpt=np.array([])

In [236]:

for i in decryp:
  for j in i:
    for key in letter_index:
      if letter_index[key]==j:
        print(key)
        outpt=np.append(outpt,key)

M
I


In [237]:
outpt

array(['M', 'I'], dtype='<U32')

In [238]:
for values in outpt:
  output_str=output_str+values

In [239]:
output_str

'your decryped value is :MI'